modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Mrbysco/Tired/issues"
license="MIT"

[[mods]]
modId="tired"
version="${file.jarVersion}"
displayName="Tired"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tired"
authors="Mrbysco"
description='''
I just want to sleep, let me sleep!
'''
[[dependencies.tired]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"