modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Tired/issues"
license="MIT"

[[mods]]
modId="tired"
version="${file.jarVersion}"
displayName="Tired"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tired"
authors="Mrbysco"
description='''
I just want to sleep, let me sleep!
'''
[[dependencies.tired]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.tired]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"